import {
  Account,
  Keypair,
  Networks,
  Operation,
  Transaction,
  TransactionBuilder,
} from '@stellar/stellar-sdk';

/**
 * SEP-10 Web Authentication Example
 *
 * SEP-10 Architecture Overview:
 * ─────────────────────────────
 * SEP-10 (Web Authentication) defines a standard challenge-response protocol
 * that lets a Stellar account holder prove key ownership to any service (anchor,
 * exchange, wallet hub) WITHOUT broadcasting a transaction or spending fees.
 *
 * The complete lifecycle has four phases:
 *
 *  1. Challenge Generation  (server side)
 *     The server creates a Stellar transaction with:
 *       - Source account: the server's signing key
 *       - Sequence number: 0 (non-replayable; never submitted on-chain)
 *       - Time bounds: short-lived (typically 15 minutes)
 *       - First operation: manage_data — key = "<home_domain> auth",
 *         value = 32 random bytes (nonce)
 *       - Optional web_auth_domain operation if served from a different domain
 *     The challenge XDR and network passphrase are returned to the client.
 *
 *  2. Challenge Verification  (client + server)
 *     The client MUST verify:
 *       a. Network passphrase matches the expected network.
 *       b. Server signing key is the one listed in stellar.toml.
 *       c. Sequence number is 0.
 *       d. Time bounds exist and the challenge has not expired.
 *       e. First operation is manage_data with the correct home domain key.
 *       f. Server signature over the transaction hash is valid.
 *
 *  3. Client Signing
 *     The client signs the challenge transaction with the account key it is
 *     authenticating. For multisig accounts, all required co-signers sign.
 *     The signed XDR is POSTed back to the server's auth endpoint.
 *
 *  4. Token Exchange  (server side)
 *     The server verifies the returned signatures meet the account's signing
 *     thresholds, then issues a short-lived JWT bound to the account address.
 *     All subsequent SEP-24 / SEP-12 / SEP-31 calls carry this JWT.
 *
 * Security Considerations:
 * ────────────────────────
 *  • Sequence number 0 guarantees the challenge can NEVER be submitted on-chain
 *    as a real transaction (would always fail with tx_bad_seq).
 *  • The nonce (32-byte random value) prevents replay of older challenges.
 *  • Short time bounds (15 min default) limit the window for stolen challenges.
 *  • Always verify the server's signing key against the anchor's stellar.toml
 *    before signing, to prevent man-in-the-middle substitution attacks.
 *  • JWTs are short-lived (typically 24 h) and scoped to a single account.
 *
 * This example targets the SDF-maintained public testnet anchor at
 * https://testanchor.stellar.org which implements SEP-10 in full.
 */

// ─── Types ────────────────────────────────────────────────────────────────────

interface StellarToml {
  SIGNING_KEY?: string;
  WEB_AUTH_ENDPOINT?: string;
  NETWORK_PASSPHRASE?: string;
}

interface ChallengeResponse {
  transaction: string;
  network_passphrase: string;
}

interface TokenResponse {
  token: string;
}

/** Decoded JWT payload (without cryptographic verification — educational only). */
interface JwtPayload {
  iss?: string;
  sub?: string;
  iat?: number;
  exp?: number;
  jti?: string;
  [key: string]: unknown;
}

// ─── Constants ────────────────────────────────────────────────────────────────

const ANCHOR_DOMAIN = 'testanchor.stellar.org';
const ANCHOR_TOML_URL = `https://${ANCHOR_DOMAIN}/.well-known/stellar.toml`;

// ─── Helpers ─────────────────────────────────────────────────────────────────

/**
 * Minimal stellar.toml parser — extracts only the fields needed for SEP-10.
 */
async function fetchStellarToml(tomlUrl: string): Promise<StellarToml> {
  const res = await fetch(tomlUrl);
  if (!res.ok) {
    throw new Error(`stellar.toml fetch failed (${res.status}): ${tomlUrl}`);
  }
  const text = await res.text();

  const parsed: StellarToml = {};
  for (const raw of text.split('\n')) {
    const line = raw.trim();
    const signingKey = line.match(/^SIGNING_KEY\s*=\s*"(.+?)"/);
    const webAuth = line.match(/^WEB_AUTH_ENDPOINT\s*=\s*"(.+?)"/);
    const netPhrase = line.match(/^NETWORK_PASSPHRASE\s*=\s*"(.+?)"/);
    if (signingKey) parsed.SIGNING_KEY = signingKey[1];
    if (webAuth) parsed.WEB_AUTH_ENDPOINT = webAuth[1];
    if (netPhrase) parsed.NETWORK_PASSPHRASE = netPhrase[1];
  }
  return parsed;
}

/**
 * Step 1 (simulated server-side): Build a SEP-10 challenge transaction.
 *
 * In production this is generated by the anchor's server. We replicate it here
 * locally with a server keypair so the entire lifecycle is self-contained and
 * runnable without a real anchor, then also show the real-anchor flow for
 * comparison.
 *
 * Challenge structure per SEP-10 spec:
 *   - sourceAccount = server signing key
 *   - sequence      = 0  ← never submittable on-chain
 *   - timeBounds    = [now, now + 15 min]
 *   - operations[0] = manage_data("<home_domain> auth", <32-byte nonce>)
 *                       with source = client account
 *   - operations[1] = manage_data("web_auth_domain", <anchor domain>)
 *                       with source = server key  (optional per spec)
 */
function buildChallengeTransaction(
  serverKeypair: Keypair,
  clientPublicKey: string,
  homeDomain: string,
  networkPassphrase: string,
): Transaction {
  // A sequence-0 account object is used so the transaction is never submittable
  const serverAccount = new Account(serverKeypair.publicKey(), '-1'); // seq -1 → built tx gets seq 0

  // 32-byte nonce encoded as base64
  const nonce = Buffer.from(crypto.getRandomValues(new Uint8Array(32)));

  const now = Math.floor(Date.now() / 1000);
  const { Operation } = require('@stellar/stellar-sdk');

  const tx = new TransactionBuilder(serverAccount, {
    fee: '100',
    networkPassphrase,
  })
    .addOperation(
      // Primary challenge operation: client account must sign this
      Operation.manageData({
        name: `${homeDomain} auth`,
        value: nonce,
        source: clientPublicKey,
      }),
    )
    .addOperation(
      // Optional web_auth_domain operation signed by server (proves domain ownership)
      Operation.manageData({
        name: 'web_auth_domain',
        value: Buffer.from(homeDomain),
        source: serverKeypair.publicKey(),
      }),
    )
    .setTimebounds(now, now + 900) // 15-minute validity window
    .build();

  // Server signs the challenge
  tx.sign(serverKeypair);
  return tx;
}

/**
 * Step 2: Verify a challenge transaction (client-side validation).
 *
 * Checks performed (subset of full SEP-10 spec validation):
 *   ✓  Network passphrase matches
 *   ✓  Sequence number is 0 (not submittable on-chain)
 *   ✓  Time bounds are present and challenge has not expired
 *   ✓  First operation is manage_data with the expected home domain key
 *   ✓  First operation's source is the authenticating account
 *   ✓  Server's signature over the transaction hash is valid
 *
 * Throws with a descriptive message if any check fails.
 */
function verifyChallengeTransaction(
  tx: Transaction,
  serverPublicKey: string,
  clientPublicKey: string,
  homeDomain: string,
  networkPassphrase: string,
): void {
  const { hash: stellarHash } = require('@stellar/stellar-sdk');

  // 1. Network passphrase
  if (tx.networkPassphrase !== networkPassphrase) {
    throw new Error(
      `Network mismatch: expected "${networkPassphrase}", got "${tx.networkPassphrase}"`,
    );
  }

  // 2. Sequence number must be 0
  if (tx.sequence !== '0') {
    throw new Error(`Challenge sequence must be 0 (non-submittable), got ${tx.sequence}`);
  }

  // 3. Time bounds
  if (!tx.timeBounds) {
    throw new Error('Challenge transaction must have time bounds');
  }
  const nowSec = Math.floor(Date.now() / 1000);
  if (nowSec > Number(tx.timeBounds.maxTime)) {
    throw new Error(`Challenge has expired (maxTime=${tx.timeBounds.maxTime}, now=${nowSec})`);
  }
  if (nowSec < Number(tx.timeBounds.minTime)) {
    throw new Error(`Challenge is not yet valid (minTime=${tx.timeBounds.minTime}, now=${nowSec})`);
  }

  // 4. First operation must be manage_data with correct key
  const ops = tx.operations;
  if (ops.length === 0) {
    throw new Error('Challenge has no operations');
  }
  const firstOp = ops[0];
  if (firstOp.type !== 'manageData') {
    throw new Error(`First operation must be manage_data, got ${firstOp.type}`);
  }
  const expectedKey = `${homeDomain} auth`;
  if ((firstOp as any).name !== expectedKey) {
    throw new Error(
      `First manage_data key must be "${expectedKey}", got "${(firstOp as any).name}"`,
    );
  }

  // 5. First operation source must be the authenticating client
  if (firstOp.source !== clientPublicKey) {
    throw new Error(
      `First operation source must be client key ${clientPublicKey}, got ${firstOp.source}`,
    );
  }

  // 6. Verify server signature
  const txHash = tx.hash();
  const serverKp = Keypair.fromPublicKey(serverPublicKey);
  const serverSig = tx.signatures.find((sig) => {
    try {
      return serverKp.verify(txHash, sig.signature());
    } catch {
      return false;
    }
  });
  if (!serverSig) {
    throw new Error('Challenge is not signed by the declared server key');
  }
}

/**
 * Step 3: Client signs the challenge and serializes it for transport.
 */
function signChallenge(tx: Transaction, clientKeypair: Keypair): string {
  tx.sign(clientKeypair);
  return tx.toXDR();
}

/**
 * Simulated server-side token issuance.
 *
 * In production the server would:
 *   1. Deserialize the signed XDR.
 *   2. Verify all client signatures meet the account's signing thresholds.
 *   3. Issue a JWT via a proper signing library.
 *
 * Here we craft a plain JWT-shaped payload to illustrate the structure without
 * an external library dependency.
 */
function issueSimulatedJwt(
  clientPublicKey: string,
  serverDomain: string,
  challengeTx: Transaction,
): string {
  const now = Math.floor(Date.now() / 1000);
  const payload: JwtPayload = {
    iss: `https://${serverDomain}/auth`,
    sub: clientPublicKey,
    iat: now,
    exp: now + 86400, // 24-hour token lifetime
    jti: `${challengeTx.hash().toString('hex').slice(0, 16)}`, // ties token to challenge
  };

  // Base64url encode — no real cryptographic signing (educational demo only)
  const header = Buffer.from(JSON.stringify({ alg: 'HS256', typ: 'JWT' })).toString('base64url');
  const body = Buffer.from(JSON.stringify(payload)).toString('base64url');
  const signature = Buffer.from('<simulated-signature>').toString('base64url');
  return `${header}.${body}.${signature}`;
}

/**
 * Decode and display a JWT payload without verifying the signature.
 * In production always verify the JWT with the server's public key.
 */
function decodeJwtPayload(token: string): JwtPayload {
  const parts = token.split('.');
  if (parts.length !== 3) throw new Error('Malformed JWT: expected 3 dot-separated parts');
  return JSON.parse(Buffer.from(parts[1], 'base64url').toString('utf8')) as JwtPayload;
}

/**
 * Inspect and display a challenge transaction's structure for educational purposes.
 */
function inspectChallengeTransaction(tx: Transaction): void {
  console.log('  Transaction details:');
  console.log(`    Source account:   ${tx.source}`);
  console.log(`    Sequence number:  ${tx.sequence} (must be 0)`);
  console.log(
    `    Time bounds:      minTime=${tx.timeBounds?.minTime ?? 'none'}, maxTime=${tx.timeBounds?.maxTime ?? 'none'}`,
  );
  console.log(`    Signature count:  ${tx.signatures.length} (server pre-signed)`);
  console.log(`    Operations (${tx.operations.length}):`);
  for (let i = 0; i < tx.operations.length; i++) {
    const op = tx.operations[i] as any;
    if (op.type === 'manageData') {
      const valuePreview =
        op.value instanceof Buffer ? `<${op.value.length} bytes>` : String(op.value).slice(0, 32);
      console.log(`      [${i}] manage_data  name="${op.name}"  value=${valuePreview}`);
      if (op.source) console.log(`           source=${op.source}`);
    } else {
      console.log(`      [${i}] ${op.type}`);
    }
  }
  console.log(`    XDR (first 80 chars): ${tx.toXDR().slice(0, 80)}...`);
}

// ─── Live Anchor Flow ─────────────────────────────────────────────────────────

/**
 * Performs the real SEP-10 challenge-response flow against the testnet anchor.
 * Returns a live JWT if successful, or null on any network error.
 */
async function runLiveAnchorFlow(
  clientKeypair: Keypair,
  toml: StellarToml,
): Promise<string | null> {
  if (!toml.WEB_AUTH_ENDPOINT || !toml.SIGNING_KEY) return null;

  const webAuthEndpoint = toml.WEB_AUTH_ENDPOINT;
  const networkPassphrase = toml.NETWORK_PASSPHRASE || Networks.TESTNET;

  // Step A — GET challenge
  const challengeUrl = `${webAuthEndpoint}?account=${clientKeypair.publicKey()}&home_domain=${ANCHOR_DOMAIN}`;
  const challengeRes = await fetch(challengeUrl);
  if (!challengeRes.ok) {
    console.log(
      `    Anchor challenge request failed (${challengeRes.status}) — skipping live flow`,
    );
    return null;
  }
  const challengeData = (await challengeRes.json()) as ChallengeResponse;

  // Step B — Deserialize
  const challengeTx = TransactionBuilder.fromXDR(
    challengeData.transaction,
    challengeData.network_passphrase || networkPassphrase,
  );
  if (!('sign' in challengeTx)) {
    console.log('    Anchor returned a FeeBumpTransaction — not supported for SEP-10');
    return null;
  }

  // Step C — Verify challenge
  verifyChallengeTransaction(
    challengeTx as Transaction,
    toml.SIGNING_KEY,
    clientKeypair.publicKey(),
    ANCHOR_DOMAIN,
    challengeData.network_passphrase || networkPassphrase,
  );

  // Step D — Sign
  (challengeTx as Transaction).sign(clientKeypair);
  const signedXdr = (challengeTx as Transaction).toXDR();

  // Step E — POST for JWT
  const tokenRes = await fetch(webAuthEndpoint, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ transaction: signedXdr }),
  });
  if (!tokenRes.ok) {
    const body = await tokenRes.text();
    console.log(`    Token exchange failed (${tokenRes.status}): ${body} — skipping live flow`);
    return null;
  }
  const tokenData = (await tokenRes.json()) as TokenResponse;
  return tokenData.token;
}

// ─── Main Entry Point ─────────────────────────────────────────────────────────

export async function run(): Promise<void> {
  console.log('═══════════════════════════════════════════════════════════');
  console.log('  SEP-10 Web Authentication Example');
  console.log('═══════════════════════════════════════════════════════════');
  console.log(`  Anchor domain:  ${ANCHOR_DOMAIN}`);
  console.log(`  Network:        Stellar Testnet`);
  console.log('───────────────────────────────────────────────────────────\n');

  // ── Step 1: Generate keypairs ──────────────────────────────────────────────
  console.log('Step 1: Generating keypairs...');
  const serverKeypair = Keypair.random(); // simulates anchor's signing key
  const clientKeypair = Keypair.random(); // simulates wallet user

  console.log(`  Server (anchor) signing key: ${serverKeypair.publicKey()}`);
  console.log(`  Client (wallet) public key:  ${clientKeypair.publicKey()}`);

  // ── Step 2: Server generates challenge ────────────────────────────────────
  console.log('\nStep 2: Server generates SEP-10 challenge transaction...');
  const challengeTx = buildChallengeTransaction(
    serverKeypair,
    clientKeypair.publicKey(),
    ANCHOR_DOMAIN,
    Networks.TESTNET,
  );
  console.log('  Challenge transaction built successfully.');
  inspectChallengeTransaction(challengeTx);

  // ── Step 3: Client verifies the challenge ─────────────────────────────────
  console.log('\nStep 3: Client verifies the challenge transaction...');
  console.log('  Security checks performed:');
  try {
    verifyChallengeTransaction(
      challengeTx,
      serverKeypair.publicKey(),
      clientKeypair.publicKey(),
      ANCHOR_DOMAIN,
      Networks.TESTNET,
    );
    console.log('    ✓ Network passphrase matches Stellar Testnet');
    console.log('    ✓ Sequence number is 0 (challenge cannot be submitted on-chain)');
    console.log('    ✓ Time bounds present and challenge is within validity window');
    console.log(`    ✓ First operation is manage_data with key "${ANCHOR_DOMAIN} auth"`);
    console.log('    ✓ First operation source matches client public key');
    console.log('    ✓ Server signature over transaction hash is valid');
    console.log('  Challenge verification passed.');
  } catch (err: any) {
    throw new Error(`Challenge verification failed: ${err.message}`);
  }

  // ── Step 3b: Demonstrate tampered challenge rejection ─────────────────────
  console.log('\nStep 3b: Demonstrating rejection of a tampered challenge...');
  const rogue = Keypair.random();
  try {
    verifyChallengeTransaction(
      challengeTx,
      rogue.publicKey(), // wrong server key
      clientKeypair.publicKey(),
      ANCHOR_DOMAIN,
      Networks.TESTNET,
    );
    throw new Error('Expected tampered challenge to be rejected');
  } catch (err: any) {
    if (err.message.startsWith('Expected tampered')) throw err;
    console.log(`  ✓ Tampered challenge correctly rejected: "${err.message}"`);
  }

  // ── Step 4: Client signs the challenge ────────────────────────────────────
  console.log('\nStep 4: Client signs the challenge transaction...');
  const signedXdr = signChallenge(challengeTx, clientKeypair);
  console.log(`  Signed XDR length:   ${signedXdr.length} characters`);
  console.log(`  Total signatures:    ${challengeTx.signatures.length} (server + client)`);
  console.log(`  Signed XDR preview:  ${signedXdr.slice(0, 80)}...`);

  // ── Step 5: Server verifies signatures and issues JWT ────────────────────
  console.log('\nStep 5: Server verifies client signatures and issues JWT...');

  // Re-deserialize from XDR (simulates receiving the POSTed body)
  const returnedTx = TransactionBuilder.fromXDR(signedXdr, Networks.TESTNET) as Transaction;

  // Confirm the client signature is present and valid
  const txHash = returnedTx.hash();
  const clientKp = Keypair.fromPublicKey(clientKeypair.publicKey());
  const clientSig = returnedTx.signatures.find((sig) => {
    try {
      return clientKp.verify(txHash, sig.signature());
    } catch {
      return false;
    }
  });

  if (!clientSig) {
    throw new Error('Client signature not found on returned transaction');
  }
  console.log('  ✓ Client signature verified against transaction hash');
  console.log('  ✓ Signing thresholds met (single-key account: weight 1 ≥ low threshold 1)');

  const jwt = issueSimulatedJwt(clientKeypair.publicKey(), ANCHOR_DOMAIN, returnedTx);
  console.log('  JWT issued successfully.');

  // ── Step 6: Inspect JWT payload ───────────────────────────────────────────
  console.log('\nStep 6: Inspecting JWT payload...');
  const payload = decodeJwtPayload(jwt);
  console.log('  Decoded JWT claims:');
  console.log(`    iss (issuer):    ${payload.iss}`);
  console.log(`    sub (subject):   ${payload.sub}`);
  if (payload.iat) {
    console.log(`    iat (issued at): ${new Date(payload.iat * 1000).toISOString()}`);
  }
  if (payload.exp) {
    console.log(`    exp (expires):   ${new Date(payload.exp * 1000).toISOString()}`);
  }
  if (payload.jti) {
    console.log(`    jti (challenge): ${payload.jti}`);
  }
  console.log("  Note: In production, verify the JWT signature with the server's public key");
  console.log('        before trusting any claim. This demo uses a simulated signature.');

  // ── Step 7: Expiry validation demonstration ───────────────────────────────
  console.log('\nStep 7: Demonstrating challenge expiration detection...');
  const serverKpForExpiry = Keypair.random();
  const clientKpForExpiry = Keypair.random();
  const expiredServerAccount = new Account(serverKpForExpiry.publicKey(), '-1');
  const expiredTx = new TransactionBuilder(expiredServerAccount, {
    fee: '100',
    networkPassphrase: Networks.TESTNET,
  })
    .addOperation(
      Operation.manageData({
        name: `${ANCHOR_DOMAIN} auth`,
        value: Buffer.from(crypto.getRandomValues(new Uint8Array(32))),
        source: clientKpForExpiry.publicKey(),
      }),
    )
    .setTimebounds(1, 2) // expired in the past
    .build();
  expiredTx.sign(serverKpForExpiry);

  try {
    verifyChallengeTransaction(
      expiredTx as Transaction,
      serverKpForExpiry.publicKey(),
      clientKpForExpiry.publicKey(),
      ANCHOR_DOMAIN,
      Networks.TESTNET,
    );
    throw new Error('Expected expired challenge to be rejected');
  } catch (err: any) {
    if (err.message.startsWith('Expected expired')) throw err;
    console.log(`  ✓ Expired challenge correctly rejected: "${err.message}"`);
  }

  // ── Step 8: Live anchor flow ───────────────────────────────────────────────
  console.log('\nStep 8: Running live SEP-10 flow against testnet anchor...');
  console.log(`  Fetching anchor config from ${ANCHOR_TOML_URL}...`);

  let liveJwt: string | null = null;
  try {
    const toml = await fetchStellarToml(ANCHOR_TOML_URL);

    if (toml.WEB_AUTH_ENDPOINT && toml.SIGNING_KEY) {
      console.log(`  WEB_AUTH_ENDPOINT: ${toml.WEB_AUTH_ENDPOINT}`);
      console.log(`  SIGNING_KEY:       ${toml.SIGNING_KEY.slice(0, 20)}...`);
      console.log('  Requesting challenge from anchor...');
      liveJwt = await runLiveAnchorFlow(clientKeypair, toml);
    } else {
      console.log(
        '  stellar.toml is missing WEB_AUTH_ENDPOINT or SIGNING_KEY — skipping live flow',
      );
    }
  } catch (err: any) {
    console.log(`  Live anchor flow skipped (network error): ${err.message}`);
  }

  if (liveJwt) {
    console.log('  ✓ Live JWT obtained from testnet anchor.');
    const livePayload = decodeJwtPayload(liveJwt);
    console.log(`    sub: ${livePayload.sub ?? '(not present)'}`);
    console.log(
      `    exp: ${livePayload.exp ? new Date(livePayload.exp * 1000).toISOString() : '(not present)'}`,
    );
  } else {
    console.log('  Live flow skipped — simulated flow above demonstrates the full lifecycle.');
  }

  // ── Final summary ──────────────────────────────────────────────────────────
  console.log('\n═══════════════════════════════════════════════════════════');
  console.log('  SEP-10 Authentication Example Complete');
  console.log('═══════════════════════════════════════════════════════════');
  console.log('  What was demonstrated:');
  console.log('    ✓ Server generated a SEP-10 challenge transaction');
  console.log('    ✓ Challenge structure inspected (sequence=0, timeBounds, manageData)');
  console.log('    ✓ Client verified the challenge (network, sequence, timeBounds, sig)');
  console.log('    ✓ Tampered challenge was correctly rejected');
  console.log('    ✓ Client signed the challenge to prove key ownership');
  console.log('    ✓ Server verified client signature and issued a JWT');
  console.log('    ✓ JWT payload decoded and claims explained');
  console.log('    ✓ Expired challenge was correctly rejected');
  console.log(
    liveJwt
      ? '    ✓ Live JWT obtained from testnet anchor'
      : '    ✓ Live anchor flow attempted (testnet connectivity optional)',
  );
  console.log('\n  SEP-10 reference: https://stellar.org/protocol/sep-10');
  console.log('═══════════════════════════════════════════════════════════\n');
}
